<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function ($,modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Check Account',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
        window.checkPaytabsAccount = function(){
            $('body').append('<div class="paytabs-popup"><?php echo $this->getAjaxCheckUrl() ?></div>');
            var popup = modal(options, $('.paytabs-popup'));
            $('.paytabs-popup').modal('openModal');

            $(".modal-inner-wrap").css("max-width",'35%');
        }
    });
</script>

<?php echo $block->getButtonHtml() ?>